### ISSUE TITLE
Python snippets/SDK reports unauthenticated

### ISSUE THREAD

**Issue by lukekim** [spiceai/spicepy#13]
- https://canary.discord.com/channels/803820740868571196/958913700562108447/963582946525200394
- https://colab.research.google.com/drive/1Bnbit7qOizhJMrDY-Ev_lmU9YZvDYIyd?usp=sharing
- https://www.kaggle.com/code/spiceluke/spice-xyz-ethereum-blocks/edit/run/92410059

- [x] https://github.com/spicehq/snippets-python-base/pull/2

**Comment by phillipleblanc** [comment]
I've updated the snippet in this PR: https://github.com/spicehq/snippets-python-base/pull/2

I've retested the Kaggle/Colab notebooks and they are working when resolving to the updated commit with the SDK fix.
