### ISSUE TITLE
Don't override `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH`

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spicepy#18]
By default, `spice-py` will override the environment variable `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` to the LetsEncrypt root certificate. While this works for Spice, it will break other python libraries that depend on gRPC and need to connect to endpoints which aren't secured by LetsEncrypt, i.e. Google BigQuery.

**Comment by lukekim** [comment]
We should not set an environment variable, but pass the detected file path directly to pyarrow.
