### ISSUE TITLE
Ctrl-C doesn't cancel a long running query

### ISSUE THREAD

**Issue by johnnyg** [spiceai/spicepy#38]
Example query:
```python
from spicepy import Client

client = Client(...)
reader = client.query('select * from eth.logs order by block_number desc')
```

Spicepy version: `spicepy @ git+https://github.com/spiceai/spicepy@0b11bbd4c305fd46c5a150b00618372c39aacba9`

**Comment by robin-vjc** [comment]
Fixed in https://github.com/spiceai/spicepy/pull/39
